# Generated by Django 6.1.1 on 2026-09-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentroster',
            name='source',
            field=models.CharField(choices=[('admin', 'Enrolled by admin (pre-verified)'), ('self', 'Submitted by student at signup (needs admin approval)')], default='admin', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentroster',
            name='activation_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
