# Generated by Django 6.1.1 on 2026-09-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_teacherprofile_address_teacherprofile_cnic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='shift_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='shift_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
