# Generated by Django 6.1.1 on 2026-09-19 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('accounts', '0004_teacherprofile_shift_end_teacherprofile_shift_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentroster',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_rosters', to='academics.schoolclass'),
        ),
    ]
