# Generated by Django 6.1.1 on 2026-09-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_studentroster_school_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='rate_per_lecture',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
