# Generated by Django 6.1.1 on 2026-09-20 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_teacherprofile_rate_per_lecture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='whatsapp_number',
        ),
    ]
