# Generated by Django 6.0.4 on 2026-09-20 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_teacherprofile_whatsapp_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='rate_per_lecture',
        ),
    ]
