# Generated by Django 6.1.1 on 2026-09-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_teachertask'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentroster',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
