# Generated by Django 6.1.1 on 2026-09-20 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='paid_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='school_class',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_structure', to='academics.schoolclass'),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='class_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
