# Generated by Django 6.0.4 on 2026-10-03 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('bio', models.CharField(blank=True, max_length=240)),
                ('photo', models.TextField(blank=True)),
                ('email_updates', models.BooleanField(default=True)),
                ('class_reminders', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
