# Generated by Django 6.0.4 on 2026-09-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=120)),
                ('guardian_name', models.CharField(blank=True, max_length=120)),
                ('guardian_phone', models.CharField(max_length=30)),
                ('intended_class', models.CharField(max_length=50)),
                ('current_school', models.CharField(blank=True, max_length=150)),
                ('subjects', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('walk_in', 'Walk-in'), ('phone', 'Phone call'), ('social', 'Social media'), ('website', 'Website')], default='walk_in', max_length=10)),
                ('status', models.CharField(choices=[('new', 'New lead'), ('trial', 'Trial class assigned'), ('follow_up', 'Follow-up call'), ('enrolled', 'Enrolled'), ('dropped', 'Dropped')], default='new', max_length=10)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
